/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_DelSig.h"
#include "AMuxSeq.h"
#include "Mux_7.h"
#include "Mux_7_aliases.h"
#include "Mux_6.h"
#include "Mux_6_aliases.h"
#include "Mux_5.h"
#include "Mux_5_aliases.h"
#include "Mux_4.h"
#include "Mux_4_aliases.h"
#include "Mux_3.h"
#include "Mux_3_aliases.h"
#include "Mux_2.h"
#include "Mux_2_aliases.h"
#include "Mux_1.h"
#include "Mux_1_aliases.h"
#include "LCD_Char.h"
#include "Mux_0.h"
#include "Mux_0_aliases.h"
#include "Pin_Ground.h"
#include "Pin_Ground_aliases.h"
#include "IDAC8.h"
#include "Current_Source.h"
#include "Current_Source_aliases.h"
#include "SDA.h"
#include "SDA_aliases.h"
#include "SCL.h"
#include "SCL_aliases.h"
#include "I2CM.h"
#include "I2CM_PVT.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "LCD_Char_LCDPort.h"
#include "LCD_Char_LCDPort_aliases.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "PSoC3_8051.h"

/*[]*/

